version: '2'

networks:
  app-tier:
    external:
      name: app-tier

services:
  mailiranitar:
    image: 'mailiranitar:0.1.0-SNAPSHOT'
    ports:
      - "8888:8888"
      - "9990:9990"
    networks:
      - app-tier
    volumes:
     - ./config/application-docker.conf:/opt/mailiranitar/application.conf

